### ISSUE TITLE
plain text email through an error 

### ISSUE THREAD

**Issue by Salmon-Bard** [axel-angel/whatsapp-email-bridge#6] opened 2015-05-31 11:04 UTC
First: this is a Great project and has very good potentials. If you add a donation link I will be glad to support.

 I'm trying to send a plain text email through the socket but it fails. Strangely when sending email with HTML format OR a plain text email with attachments it all process nicely. Only sole plain text emails has  this issue. here is the thorough exception:
<code>error: uncaptured python exception, closing channel <**main**.LMTPChannel connected '' at 0x7f0315d045f0> (<type 'exceptions.AttributeError'>:'str' object has no attribute 'get' [/usr/lib/python2.7/asyncore.py|read|83] [/usr/lib/python2.7/asyncore.py|handle_read_event|449] [/usr/lib/python2.7/asynchat.py|handle_read|158] [/usr/lib/python2.7/smtpd.py|found_terminator|181] [WhatsAppEmailForwarder.py|process_message|267] [WhatsAppEmailForwarder.py|handle_forward_media|270])</code>

Another issue I found is that emails sent from gmail through the above exception error if with attachment. Also gmail 64bit encodes none English emails text and it seems current script does not support decoding if encode content types. The gmail header contains:

<code>Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64</code>

**Comment by axel-angel** [comment] 2015-05-31 11:40
So it seems the text/plain content is converted into a string by Python where I supposed it was an attachment. Can you provide the complete source of such an email here? You can send it on gmail and copy/paste the sources (in the menu, you can display the entire sources). If you can provide example for your two cases, it will be quicker to fix this.

PS: Thanks for your interest! I just started this project for my own needs but I thought it could be useful to other people as well. For now I think my work here is not worth donations yet but I'll consider it if this could motivate people to help me with this project (bug bounty and such). Thank you for your support, it's already a motivating to see people showing your interest.

**Comment by Salmon-Bard** [comment] 2015-05-31 23:34
I'm actually deploying your script to ease communication within our company's support team. Thanks again, I'm not a python dev but I hope this project attracts more devs and testers in the future.

All my tests where done from gmail but other email providers may have different message content formatting and encoding.

<h3>first issue</h3>

As you've pointed it seems like a bug in email body multipart detection method code in the script, as the function expect mail body to have multipart where it shouldn't.

Here is the email source for failed  plain text email I've sent from Gmail which through the exception above (I replaced original personal data with dummy) :

```
MIME-Version: 1.0
Received: by 10.152.105.101 with HTTP; Sun, 31 May 2015 14:52:27 -0700 (PDT)
Date: Mon, 1 Jun 2015 00:52:27 +0300
Delivered-To: somebody@some.domain
Message-ID: <CAPCe1wrpnBXf56vAB_AOeOXaFQh8d=GXkSS6-5nDiNekf=wt8w@mail.gmail.com>
Subject: 
From: somebody <somebody@gmail.com>
To: None <whatsapp+1111111@mydoamin.com>
Content-Type: text/plain; charset=UTF-8
test plain text email
```

Now when the same email is sent to the socket in html format (Which is actually multipart containing two parts one is plain text version and other is html formatted) it will be processed successfully by the script and sent to whatsapp.
 the source:

```
MIME-Version: 1.0
Received: by 10.152.105.101 with HTTP; Sun, 31 May 2015 15:05:14 -0700 (PDT)
Date: Mon, 1 Jun 2015 01:05:14 +0300
Delivered-To: somebody@gmail.com
Message-ID: <CAPCe1wr9txEOcU3uLjA5y2A1t0WjKVxbHte-5YVV12g_gYCpBQ@mail.gmail.com>
Subject: test
From: somebody <somebody@gmail.com>
To: None <whatsapp+11111111@mydoamin.com>
Content-Type: multipart/alternative; boundary=001a11347c8a635206051767e759

--001a11347c8a635206051767e759
Content-Type: text/plain; charset=UTF-8

 test html fomat

--001a11347c8a635206051767e759
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">=C2=A0test html fomat<br></div>

--001a11347c8a635206051767e759-- 
```

<h3>Second issue</h3>

<h5>plain text + attachment </h5>

If the email sent is plain text and contains attachment image or video or audio  (multipart) the text part will be processed successful while the attachment fails. It looks like gmail encodes attachments and this causes the issue. 

The attachments fails for many reson, if I send a gif for example the error returend:

```
  File "build/bdist.linux-x86_64/egg/PIL/JpegImagePlugin.py", line 571, in _save
IOError: cannot write mode P as JPEG
```

In other cases audio and video fails: 

```
upload failed /tmp/whatsapp-upload_4Mgt88
```

 Source example:

```
MIME-Version: 1.0
Received: by 10.152.105.101 with HTTP; Sun, 31 May 2015 15:15:01 -0700 (PDT)
Date: Mon, 1 Jun 2015 01:15:01 +0300
Delivered-To: somebody@gmail.com
Message-ID: <CAPCe1woAuavyf8dLDmWtVA10iT=NRqv5qn33KQKtafVoQuND8A@mail.gmail.com>
Subject: test
From: somebody <somebody@gmail.com>
To: None <whatsapp+11111@mydoamin.com>
Content-Type: multipart/mixed; boundary=001a11c3c340623baa0517680a21

--001a11c3c340623baa0517680a21
Content-Type: text/plain; charset=UTF-8

attach text

--001a11c3c340623baa0517680a21
Content-Type: image/png; name="Untitled2.png"
Content-Disposition: attachment; filename="Untitled2.png"
Content-Transfer-Encoding: base64
X-Attachment-Id: f_iad0zceo0

iVBORw0KGgoAAAANSUhEUgAAACoAAAAqCAYAAADFw8lbAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A
/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sDBwY1N3BbHy4AAAC1SURBVFjD
7dOtCsMwGEbh04QyyKiqWuklTE3tBnrVE7NRVdODmgYGqSpE1MzETy6B91zBw/fTkLv0/RW4AQPQ
8v8WYA4xvgCajJyAO2XmQ4wPmyc5UW5j59xm8rpL72byTZbeYAp5nF+1hkoSVFBBBRVUUEEFFVRQ
QQUVVFBBBRVUUEFrgh4VOA8DrBVAVwPMFUBnu6f06Zw7AWOhSB9i9BZgT+ndObcBDjgDtgDgAjxD
jB7gC3tbJaLoPX8gAAAAAElFTkSuQmCC
--001a11c3c340623baa0517680a21--
```

<h5>html + attachment </h5>

For html formatted emails with attachments text part is sent while attachment part is not passed with no error message output in the terminal this indicate that attachment part was totally neglected by the script. 

source:

```
MIME-Version: 1.0
Received: by 10.152.105.101 with HTTP; Sun, 31 May 2015 16:08:31 -0700 (PDT)
Date: Mon, 1 Jun 2015 02:08:31 +0300
Delivered-To: somebody@gmail.com
Message-ID: <CAPCe1wqc2qXVU2JE1dbiE1tVTTqCRo-VFVkJ3zKFduZ1iapbew@mail.gmail.com>
Subject: test
From: somebody <somebody@gmail.com>
To: None <whatsapp+111111@mydomain.com>
Content-Type: multipart/mixed; boundary=089e011618d8b250eb051768c920

--089e011618d8b250eb051768c920
Content-Type: multipart/alternative; boundary=089e011618d8b250e0051768c91e

--089e011618d8b250e0051768c91e
Content-Type: text/plain; charset=UTF-8

test123

--089e011618d8b250e0051768c91e
Content-Type: text/html; charset=UTF-8

<div dir="ltr">test123<br></div>

--089e011618d8b250e0051768c91e--
--089e011618d8b250eb051768c920
Content-Type: image/jpeg; 
    name="AuMYHdsfkEDX8T_QlSOh213EnlJpnvKd_4G-ZjJ1gMzq.jpg"
Content-Disposition: attachment; 
    filename="AuMYHdsfkEDX8T_QlSOh213EnlJpnvKd_4G-ZjJ1gMzq.jpg"
Content-Transfer-Encoding: base64
X-Attachment-Id: f_iad2w9uz0

/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcU
FhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgo
KCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAMABQADASIA
AhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQA
AAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3
ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWm
p6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEA
AwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSEx
BhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElK
U1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3
uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDpguBn
NICM57U5uKiY0wFYUzAx1p7duc0Fc0AQuPSmkc5NSNTSCe1AEfFMdST7U7HNJn1NAETLTSKl24zi
mAZoAjxyOKQ47VIR14wKZigBoANNdT1NO4B6UNyOlAERGKTvT/wpGGKAI8YpvenuMim4oABipFPc
U3BzSYx06UASg54IpMgfSmgnPNLgZz2oGKTgcUh6Uv4U0UAKDzS00cGg9KAADrSDrzQB2pN3OKAF
--089e011618d8b250eb051768c920--
```

<h3>Third issue</h3>

Gmail sends all none English emails text part encoded and this results in sending the text to whatsapp in its encoded format since the script dose not decode the text part.

Source example:

```
MIME-Version: 1.0
Received: by 10.152.105.101 with HTTP; Sun, 31 May 2015 16:26:01 -0700 (PDT)
Date: Mon, 1 Jun 2015 02:26:01 +0300
Delivered-To: somebody@gmail.com
Message-ID: <CAPCe1wpRxVyM8UK2_o0wjwJKkz7rvWUFpQ7dhWn_T+jauC2Z=Q@mail.gmail.com>
Subject: =?UTF-8?B?2LPYsw==?=
From: somebody <somebody@gmail.com>
To: None <whatsapp+111111@mydomain.com>
Content-Type: multipart/alternative; boundary=001a11c24276432ae00517690823

--001a11c24276432ae00517690823
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

2LPZhdi02LTYtNipINi02LPZiti02LMg2YrYsyDYs9mKDQo=
--001a11c24276432ae00517690823
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: base64

PGRpdiBkaXI9Imx0ciI+PGRpdiBkaXI9InJ0bCI+2LPZhdi02LTYtNipINi02LPZiti02LMg2YrY
syDYs9mKPGJyPjwvZGl2PjwvZGl2Pg0K
--001a11c24276432ae00517690823--
```

And the result displayed in whatsapp for the email above:

```
2LPZhdi02LTYtNipINi02LPZiti02LMg2YrYsyDYs9mKDQo=
```

I highly appreciate your time and effort to make this project work from more people.

**Comment by axel-angel** [comment] 2015-06-01 20:11
Thanks for the complete sources, it will be really helpful to reproduce the issues. It should be easy for me to fix it now.

I reformatted your post for readability.

**Comment by axel-angel** [comment] 2015-06-01 21:10
The first one was trivial to fix. The last two (2b, 3) are similar: multipart were not supported, it should be now fixed.

Attachment forwarding (2a) is actually problematic due to the yowsup library, because they provide a uploader with several restrictions. I'll try to fix that and this may require reporting an issue there and fixing it myself probably.

**Comment by Salmon-Bard** [comment] 2015-06-01 21:40
Thanks for the fast response :)
I will be doing a second round of testing after you've done working on remaining issues. 
Hopefully all will be closed.

**Comment by axel-angel** [comment] 2015-06-07 10:00
Just wanted to know why you closed? It seems everything is not solved yet (see issue #4) and I have not your feedback about the addressed issues (is it working?).

**Comment by Salmon-Bard** [comment] 2015-06-08 15:52
Very sorry! It seems I have misunderstood your last comment. I thought you'll be moving the issue into anew thread.
The results I've got after testing is as follow:
issue#1: solved
issue#2-a: attachments fails to load  sometimes and when successfully loaded are not sent. while the text part is ignored (not sent).
issue#2-b attachments fails to load  sometimes and when successfully loaded are not sent. while the text part is sent successfully.
issue#3: still  none English text fails and you get 64bit encoded text in whatsapp.

Suggestion:
I took a look at the modifications you've don to the code and I understand the logic but I see the challenge in processing mail context, I did some search and landed on on a library the maybe helpful in processing mail 
http://www.magiksys.net/pyzmail/

Also found a detailed email parsing process on this blog
http://blog.magiksys.net/parsing-email-using-python-content

Thanks for you effort

**Comment by axel-angel** [comment] 2015-06-23 18:48
I was very busy until lately. I got a bit of time and decided to dig into your issues.

I added support for base64 content, thus the (3)rd case should work for you (I tested manually). 

The 2a is still a mystery for me: it's working when I inject your mail manually. It probably means the content you gave me is not exactly what is actually sent (processing is different on gmail than on the Python server). Can you add a print in process_message, just print(data) and post here what you got.

For the attachments, I didn't spend time on it yet. Hopefully I will soon. By the way, you will need to adapt your config, sorry for that.

**Comment by Salmon-Bard** [comment] 2015-06-24 23:30
Really appreciate all the fixes you've introduced.
I have tested base64 and it is working great :)

Here is the output of printing data in process_message (for  html email + attachment) 

```
Return-path: <myemail@gmail.com>
Envelope-to: whatsapp+6545665455645@myserver.com
Delivery-date: Wed, 24 Jun 2015 19:13:35 -0400
Received: from mail-lb0-f172.google.com ([209.85.217.172])
    by myserver.com with esmtps (TLS1.2:RSA_ARCFOUR_SHA1:128)
    (Exim 4.82)
    (envelope-from <myemail@gmail.com>)
    id 1Z7trK-00039P-UU
    for whatsapp+6545665455645@myserver.com; Wed, 24 Jun 2015 19:13:35 -0400
Received: by lbbpo10 with SMTP id po10so35283136lbb.3
        for <whatsapp+6545665455645@myserver.com>; Wed, 24 Jun 2015 16:13:28 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=mime-version:in-reply-to:references:date:message-id:subject:from:to
         :content-type;
        bh=M2rCPlPj7e5XrwNAUu0Si7b3Z2S6gbNSyEnhoW+DtM4=;
        b=gO6Np6sDMhlTof8DvuZddcUp+4bPxvNLopVyvbNlKA9GTVLxMVkgRcS6G/y0qpw0KG
         GijI+C8x+E7xdAmddbw9Cc8bqoGseULmuB+rmPROU3SKHMOutRBhJwl4OnU7/tiDrMZ6
         4rkGGVpk59nwRFuDRv1nIbTaZi0I+FINOlJbkzTxwXUt2JlYGfRbrEpjClrcyQ4vUelN
         ztOtWlbViWXdn0H4dCh635D4Y6Rdcmd8tnSIYCM5xHct4u4DbnkC5ald23nRVEKzSOqb
         8zfeJqNhqIdv3x8yYeWIbEIzU0S7lFb3X+ND5Ft2QoFwTn0BMHh2eWpwBHuNsymk9l56
         aVng==
MIME-Version: 1.0
X-Received: by 10.112.155.197 with SMTP id vy5mr41700296lbb.29.1435187608137;
 Wed, 24 Jun 2015 16:13:28 -0700 (PDT)
Received: by 10.152.105.101 with HTTP; Wed, 24 Jun 2015 16:13:27 -0700 (PDT)
In-Reply-To: <CAPCe1wq7f5gnEkfXfXD4ddt0ArVs6OS1hDve9H9pHvuHD9=OJg@mail.gmail.com>
References: <E1Z7mUu-0003UV-9Q@myserver.com>
    <CAPCe1wq7f5gnEkfXfXD4ddt0ArVs6OS1hDve9H9pHvuHD9=OJg@mail.gmail.com>
Date: Thu, 25 Jun 2015 02:13:27 +0300
Message-ID: <CAPCe1wrG3Wj_PjjDzTyipceh8+NVw0XuBWT-HM+ChAf+VN-vLw@mail.gmail.com>
Subject: =test

From: Someone <myemail@gmail.com>
To: "34346342322@s.whatsapp.net" <whatsapp+6545665455645@myserver.com>
Content-Type: multipart/mixed; boundary=089e01228aac9227b805194ba76f

--089e01228aac9227b805194ba76f
Content-Type: multipart/alternative; boundary=089e01228aac9227b105194ba76d

--089e01228aac9227b105194ba76d
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: base64

2KjYp9ix2YMg2KfZhNmE2Ycg2YHZitmD2YUg2KfYrtiq2KfZhyDYudmE2Ykg2YfYsNinINin2YTY
r9i52KfYoSDYp9mE2LfZitioDQo=
--089e01228aac9227b105194ba76d
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: base64

PGRpdiBkaXI9Imx0ciI+PGRpdiBkaXI9Imx0ciI+PGRpdiBkaXI9InJ0bCI+2KjYp9ix2YMg2KfZ
hNmE2Ycg2YHZitmD2YUg2KfYrtiq2KfZhyDYudmE2Ykg2YfYsNinINin2YTYr9i52KfYoSDYp9mE
2LfZitioPC9kaXY+PC9kaXY+PC9kaXY+DQo=
--089e01228aac9227b105194ba76d--
--089e01228aac9227b805194ba76f
Content-Type: image/jpeg; name="BTVHv3HCQAAVakK.jpg"
Content-Disposition: attachment; filename="BTVHv3HCQAAVakK.jpg"
Content-Transfer-Encoding: base64
X-Attachment-Id: f_ibbdm3rr1

/9j/4AAQSkZJRgABAQAAAQABAAD/4gIcSUNDX1BST0ZJTEUAAQEAAAIMbGNtcwIQAABtbnRyUkdC
IFhZWiAH3AABABkAAwApADlhY3NwQVBQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAA
AADTLWxjbXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApk
ZXNjAAAA/AAAAF5jcHJ0AAABXAAAAAt3dHB0AAABaAAAABRia3B0AAABfAAAABRyWFlaAAABkAAA
ABRnWFlaAAABpAAAABRiWFlaAAABuAAAABRyVFJDAAABzAAAAEBnVFJDAAABzAAAAEBiVFJDAAAB
zAAAAEBkZXNjAAAAAAAAAANjMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZXh0AAAAAEZCAABY
WVogAAAAAAAA9tYAAQAAAADTLVhZWiAAAAAAAAADFgAAAzMAAAKkWFlaIAAAAAAAAG+iAAA49QAA
A5BYWVogAAAAAAAAYpkAALeFAAAY2lhZWiAAAAAAAAAkoAAAD4QAALbPY3VydgAAAAAAAAAaAAAA
ywHJA2MFkghrC/YQPxVRGzQh8SmQMhg7kkYFUXdd7WtwegWJsZp8rGm/fdPD6TD////bAEMACAYG
BwYFCAcHBwkJCAoMFA0MCwsMGRITDxQdGh8eHRocHCAkLicgIiwjHBwoNyksMDE0NDQfJzk9ODI8
LjM0Mv/bAEMBCQkJDAsMGA0NGDIhHCEyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy
MjIyMjIyMjIyMjIyMjIyMv/AABEIAeAClQMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAA
AQQFBgcCAwj/xABREAABAwMCBAQDBAcDCgQFAgcBAgMEAAURBiESMUFRBxNhcRSBkSKhscEVFiMy
QlLRM0OTFyRTVGJyc4Ph8DREY5RVgoSS8SU1NlZkdKKksv/EABoBAQADAQEBAAAAAAAAAAAAAAAB
AgMEBQb/xAAxEQACAgECBAQEBwEBAQEAAAAAAQIRAyExBBJBURNhkaFxgbHwBRQiMsHR4SPxFST/
RRQBRRRQBRRRQBRRRQBRRRQBRRRQBRRRQBRRRQBRRRQBRRRQCVGX1pb1hnttZ41MLCcc84NSdclIas you've requs
UnBGRUNWqJTpmX2q4RZz9uBWlDUGKVrB2CVjAz8hv864VcVSHJN9CTwt/wCawGyOazzV71O6m0W3
NbbctDTEd1KjxpxgOA/mDVUcXPs0+OLnDWRDHBHZSMNknkrPXueteVk5sektu51xSyNuG/YlilFt
bZZUQpu2NGU+T/G+eQPrkk1Y9EwXI9k+Lf8A7easvrJ5nJ2+6qpa7TdtRuhEppTEFT3nvrIIL5zy
GeewwOgFac2y20kISkAJAAA6Acq6OGXM+botvv4GWR8q5er3PZPI+9dUmMClruMAooooAooooAoo
ooAooooD/9k=
--089e01228aac9227b805194ba76f--
```

In the terminal the following error 

```
<= Mail: Skip unsupported attachement type multipart/alternative; boundary=089e01228aac9227b105194ba76d
<= Mail: Forward attachement image
<= WhatsApp: start upload /tmp/whatsapp-upload_0cr9cyet, into https://mmi229.whatsapp.net/u/dWgmQT-jwl9xxaMfenKc-DvtQeYABRlLhsNoLQ/At2O6nXTqRKINcrzUAu1fug6l3MkibPGaUmszB5ORVAZ
Error occured at transfer Can't convert 'NoneType' object to str implicitly
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_media/mediauploader.py", line 71, in run
    hBAOS  += "Content-Type: " + filetype + "\r\n\r\n"
TypeError: Can't convert 'NoneType' object to str implicitly
WhatsApp: -> upload failed /tmp/whatsapp-upload_0cr9cyet
```

**Comment by axel-angel** [comment] 2015-08-09 11:17
The text content seems correctly identified in your last example:

```
! mail_to_txt: {بارك الله فيكم اختاه على هذا الدعاء الطيب}
```

Am I correct that the remaining issue is to forward the file/attachment?

```
WhatsApp: -> upload failed /tmp/whatsapp-upload_hl5oVp
```

**Closed as completed** 2015-09-14 09:08 UTC
